[tools]
dagger = "latest"
editorconfig-checker = "latest"
just = "latest"
pre-commit = "latest"
prettier = "latest"
shfmt = "latest"
stylua = "latest"
taplo = "latest"
yamlfmt = "latest"
yamllint = "latest"
